# build-regressions.py
#
# Code to analyse the data from the vegetative indices
#
# Simon Parsons
# University of Lincoln
# 26-03-27

# This is skeleton code to run regressions on the data that we
# generate from the vegetative indices. Still needs much to be done to
# make it fucntional (though it runs in its current state).

# Largely generated by Claude Sonnet 4.5

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import argparse
from pathlib import Path
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from datetime import datetime


def read_csv_files(file_paths):
    """
    Read one or more CSV files into pandas DataFrames.
    
    Parameters:
    -----------
    file_paths : list of str
        List of file paths to CSV files
    
    Returns:
    --------
    dict : Dictionary with file names as keys and DataFrames as values
    """
    dataframes = {}
    for file_path in file_paths:
        file_name = Path(file_path).stem
        dataframes[file_name] = pd.read_csv(file_path)
        print(f"Loaded {file_name}: {dataframes[file_name].shape}")
    
    return dataframes


def build_feature_target_vectors(df1, df2, 
                                  df1_cols, df2_cols, 
                                  target_df, target_col):
    """
    Build feature matrix and target vector from multiple dataframes.
    
    Parameters:
    -----------
    df1 : DataFrame
        First dataframe
    df2 : DataFrame
        Second dataframe
    df1_cols : list of str
        Column names to extract from df1
    df2_cols : list of str
        Column names to extract from df2
    target_df : DataFrame
        DataFrame containing the target variable
    target_col : str
        Column name for the target variable
    
    Returns:
    --------
    X : array-like
        Feature matrix
    y : array-like
        Target vector
    """
    # Extract features from each dataframe
    features_df1 = df1[df1_cols].values
    features_df2 = df2[df2_cols].values
    
    # Combine features horizontally
    X = np.hstack([features_df1, features_df2])
    
    # Extract target
    y = target_df[target_col].values
    
    return X, y


def get_regression_models():
    """
    Define a dictionary of regression models to evaluate.
    
    Returns:
    --------
    dict : Dictionary with model names as keys and model instances as values
    """
    models = {
        'LinearRegression': LinearRegression(),
        'Ridge': Ridge(alpha=1.0),
        'Lasso': Lasso(alpha=1.0),
        'ElasticNet': ElasticNet(alpha=1.0, l1_ratio=0.5),
        'DecisionTree': DecisionTreeRegressor(random_state=42, max_depth=5),
        'RandomForest': RandomForestRegressor(n_estimators=100, random_state=42, max_depth=5),
        'GradientBoosting': GradientBoostingRegressor(n_estimators=100, random_state=42, max_depth=3),
        'SVR': SVR(kernel='rbf', C=1.0, epsilon=0.1)
    }
    return models


def train_and_evaluate_regression(X, y, models=None, feature_names=None, output_file='model_results.csv'):
    """
    Train multiple regression models and compute evaluation metrics.
    
    Parameters:
    -----------
    X : array-like
        Feature matrix
    y : array-like
        Target vector
    models : dict, optional
        Dictionary of models to train. If None, uses default models.
    feature_names : list of str, optional
        Names of features for reporting
    output_file : str
        Path to output CSV file for results
    
    Returns:
    --------
    results_df : DataFrame
        DataFrame containing metrics for all models
    trained_models : dict
        Dictionary of trained models
    predictions : dict
        Dictionary of predictions for each model
    """
    if models is None:
        models = get_regression_models()
    
    results = []
    trained_models = {}
    predictions = {}
    
    print("\n" + "="*70)
    print("TRAINING AND EVALUATING MULTIPLE REGRESSION MODELS")
    print("="*70)
    
    for model_name, model in models.items():
        print(f"\nTraining {model_name}...")
        
        # Train the model
        model.fit(X, y)
        trained_models[model_name] = model
        
        # Make predictions
        y_pred = model.predict(X)
        predictions[model_name] = y_pred
        
        # Calculate metrics
        rmse = np.sqrt(mean_squared_error(y, y_pred))
        mae = mean_absolute_error(y, y_pred)
        r2 = r2_score(y, y_pred)
        
        # Store results
        result = {
            'Model': model_name,
            'RMSE': rmse,
            'MAE': mae,
            'R²': r2,
            'Timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }
        results.append(result)
        
        print(f"  RMSE: {rmse:.4f} | MAE: {mae:.4f} | R²: {r2:.4f}")
    
    # Create results DataFrame
    results_df = pd.DataFrame(results)
    
    # Sort by R² (descending)
    results_df = results_df.sort_values('R²', ascending=False).reset_index(drop=True)
    
    # Save to CSV
    results_df.to_csv(output_file, index=False)
    print(f"\n{'='*70}")
    print(f"Results saved to: {output_file}")
    print(f"{'='*70}")
    
    # Print summary table
    print("\nMODEL COMPARISON (sorted by R²):")
    print(results_df.to_string(index=False))
    print(f"{'='*70}\n")
    
    return results_df, trained_models, predictions


def plot_regression_results(y_true, predictions, results_df, output_prefix='regression'):
    """
    Plot actual vs predicted values for multiple models.
    
    Parameters:
    -----------
    y_true : array-like
        Actual target values
    predictions : dict
        Dictionary with model names as keys and predictions as values
    results_df : DataFrame
        DataFrame containing model metrics
    output_prefix : str
        Prefix for saved plot files
    """
    n_models = len(predictions)
    n_cols = 3
    n_rows = (n_models + n_cols - 1) // n_cols
    
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(15, 5 * n_rows))
    axes = axes.flatten() if n_models > 1 else [axes]
    
    # Sort models by R² for consistent plotting
    sorted_models = results_df['Model'].tolist()
    
    for idx, model_name in enumerate(sorted_models):
        y_pred = predictions[model_name]
        
        # Get metrics for this model
        model_metrics = results_df[results_df['Model'] == model_name].iloc[0]
        
        # Plot actual vs predicted
        axes[idx].scatter(y_true, y_pred, alpha=0.6, edgecolors='k', s=30)
        axes[idx].plot([y_true.min(), y_true.max()], 
                      [y_true.min(), y_true.max()], 
                      'r--', lw=2, label='Perfect Prediction')
        
        axes[idx].set_xlabel('Actual Values', fontsize=10)
        axes[idx].set_ylabel('Predicted Values', fontsize=10)
        axes[idx].set_title(f"{model_name}\nR²={model_metrics['R²']:.4f}, RMSE={model_metrics['RMSE']:.4f}", 
                           fontsize=11, fontweight='bold')
        axes[idx].legend(fontsize=8)
        axes[idx].grid(True, alpha=0.3)
    
    # Hide unused subplots
    for idx in range(len(sorted_models), len(axes)):
        axes[idx].axis('off')
    
    plt.suptitle('Regression Model Comparison: Actual vs Predicted', 
                 fontsize=16, fontweight='bold', y=1.00)
    plt.tight_layout()
    
    # Save plot
    plot_file = f"{output_prefix}_comparison.png"
    plt.savefig(plot_file, dpi=300, bbox_inches='tight')
    print(f"Plot saved to: {plot_file}")
    plt.show()
    
    # Create residual plots for top 3 models
    plot_top_residuals(y_true, predictions, results_df, output_prefix, top_n=3)


def plot_top_residuals(y_true, predictions, results_df, output_prefix='regression', top_n=3):
    """
    Plot residuals for the top N models.
    
    Parameters:
    -----------
    y_true : array-like
        Actual target values
    predictions : dict
        Dictionary with model names as keys and predictions as values
    results_df : DataFrame
        DataFrame containing model metrics
    output_prefix : str
        Prefix for saved plot files
    top_n : int
        Number of top models to plot
    """
    top_models = results_df.head(top_n)['Model'].tolist()
    
    fig, axes = plt.subplots(1, top_n, figsize=(5 * top_n, 4))
    if top_n == 1:
        axes = [axes]
    
    for idx, model_name in enumerate(top_models):
        y_pred = predictions[model_name]
        residuals = y_true - y_pred
        
        axes[idx].scatter(y_pred, residuals, alpha=0.6, edgecolors='k', s=30)
        axes[idx].axhline(y=0, color='r', linestyle='--', lw=2)
        axes[idx].set_xlabel('Predicted Values', fontsize=10)
        axes[idx].set_ylabel('Residuals', fontsize=10)
        axes[idx].set_title(f"{model_name}\nResidual Plot", fontsize=11, fontweight='bold')
        axes[idx].grid(True, alpha=0.3)
    
    plt.suptitle(f'Residual Plots - Top {top_n} Models', 
                 fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()
    
    # Save plot
    plot_file = f"{output_prefix}_residuals.png"
    plt.savefig(plot_file, dpi=300, bbox_inches='tight')
    print(f"Residual plot saved to: {plot_file}")
    plt.show()


def parse_arguments():
    """
    Parse command-line arguments.
    
    Returns:
    --------
    args : Namespace
        Parsed arguments
    """
    parser = argparse.ArgumentParser(
        description='Train and evaluate multiple regression models on CSV data.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example usage:
  python script.py file1.csv file2.csv --output results.csv
  python script.py data1.csv data2.csv data3.csv --output my_results.csv --plot-prefix my_models
        """
    )
    
    parser.add_argument(
        'csv_files',
        nargs='+',
        help='One or more CSV files to read'
    )
    
    parser.add_argument(
        '--output',
        '-o',
        default='model_results.csv',
        help='Output CSV file for model results (default: model_results.csv)'
    )
    
    parser.add_argument(
        '--plot-prefix',
        '-p',
        default='regression',
        help='Prefix for output plot files (default: regression)'
    )
    
    parser.add_argument(
        '--no-plots',
        action='store_true',
        help='Disable plotting'
    )
    
    return parser.parse_args()


def main():
    """
    Main function demonstrating the complete workflow with command-line arguments.
    """
    # Parse command-line arguments
    args = parse_arguments()
    
    print("="*70)
    print("REGRESSION MODEL COMPARISON TOOL")
    print("="*70)
    print(f"Input files: {', '.join(args.csv_files)}")
    print(f"Output file: {args.output}")
    print(f"Plot prefix: {args.plot_prefix}")
    print("="*70)
    
    # Read CSV files
    dataframes = read_csv_files(args.csv_files)
    
    # Get the first two dataframes (you can modify this logic as needed)
    df_names = list(dataframes.keys())
    
    if len(df_names) < 2:
        print("\nError: At least 2 CSV files are required.")
        return
    
    df1 = dataframes[df_names[0]]
    df2 = dataframes[df_names[1]]
    
    # Display available columns
    print(f"\nColumns in {df_names[0]}: {list(df1.columns)}")
    print(f"Columns in {df_names[1]}: {list(df2.columns)}")
    
    # For demonstration, use the first 2 columns from each dataframe
    # In practice, you would specify these or make them configurable
    df1_cols = list(df1.columns)[:2]
    df2_cols = list(df2.columns)[:2]
    
    # Use the last column of df2 as target (or specify differently)
    target_col = df2.columns[-1]
    
    print(f"\nUsing features from {df_names[0]}: {df1_cols}")
    print(f"Using features from {df_names[1]}: {df2_cols}")
    print(f"Using target: {target_col} from {df_names[1]}")
    
    # Build feature and target vectors
    X, y = build_feature_target_vectors(
        df1=df1,
        df2=df2,
        df1_cols=df1_cols,
        df2_cols=df2_cols,
        target_df=df2,
        target_col=target_col
    )
    
    feature_names = [f"{df_names[0]}_{col}" for col in df1_cols] + \
                    [f"{df_names[1]}_{col}" for col in df2_cols]
    
    # Train and evaluate multiple models
    results_df, trained_models, predictions = train_and_evaluate_regression(
        X, y, 
        feature_names=feature_names,
        output_file=args.output
    )
    
    # Plot results unless disabled
    if not args.no_plots:
        plot_regression_results(y, predictions, results_df, output_prefix=args.plot_prefix)
    
    return dataframes, trained_models, results_df


def create_sample_data():
    """
    Helper function to create sample CSV files for testing.
    """
    print("Creating sample data files...")
    
    np.random.seed(42)
    n_samples = 200
    
    # Sample data for demonstration
    df1_sample = pd.DataFrame({
        'temperature': np.random.uniform(15, 35, n_samples),
        'humidity': np.random.uniform(30, 90, n_samples),
        'pressure': np.random.uniform(980, 1020, n_samples)
    })
    
    # Create target with some relationship to features
    noise = np.random.randn(n_samples) * 5
    target = (2.5 * df1_sample['temperature'] + 
              0.8 * df1_sample['humidity'] + 
              noise + 50)
    
    df2_sample = pd.DataFrame({
        'wind_speed': np.random.uniform(0, 25, n_samples),
        'visibility': np.random.uniform(1, 10, n_samples),
        'energy_consumption': target
    })
    
    # Save sample files
    df1_sample.to_csv('sample_weather.csv', index=False)
    df2_sample.to_csv('sample_energy.csv', index=False)
    
    print("Created sample_weather.csv and sample_energy.csv")
    print("\nTo run with sample data, use:")
    print("  python script.py sample_weather.csv sample_energy.csv")


if __name__ == "__main__":
    import sys
    
    # If no arguments provided, create sample data and show usage
    if len(sys.argv) == 1:
        print("No CSV files specified.\n")
        create_sample_data()
        print("\n" + "="*70)
        print("USAGE EXAMPLES:")
        print("="*70)
        print("python script.py sample_weather.csv sample_energy.csv")
        print("python script.py file1.csv file2.csv --output my_results.csv")
        print("python script.py data1.csv data2.csv --plot-prefix analysis --no-plots")
        print("="*70)
    else:
        dataframes, models, results = main()
