# build-regressions.py
#
# Code to analyse the data from the vegetative indices
#
# Simon Parsons
# University of Lincoln
# 26-03-27

# This is skeleton code to run regressions on the data that we
# generate from the vegetative indices. An initial version that only
# deals with numerical features and so can't handle soil and saline
# treatment.

# Still needs work (though it runs in its current state). In
# particular, note that the main function is really just a
# demonstration of how to assemble the various elements, and is still
# rather hard-coded.

# Largely generated by Claude Sonnet 4.5

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import argparse
from pathlib import Path
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR, LinearSVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from datetime import datetime
# Use XGBoost to get categorical variable support
from xgboost import XGBRegressor


def read_csv_files(file_paths):
    """
    Read one or more CSV files into pandas DataFrames.
    
    Parameters:
    -----------
    file_paths : list of str
        List of file paths to CSV files
    
    Returns:
    --------
    dict : Dictionary with file names as keys and DataFrames as values
    """
    dataframes = {}
    for file_path in file_paths:
        file_name = Path(file_path).stem
        dataframes[file_name] = pd.read_csv(file_path)
        print(f"Loaded {file_name}: {dataframes[file_name].shape}")
    
    return dataframes


def build_feature_target_vectors(df1, df2, feature_sets, target_df, target_col):
    """
    Build multiple feature matrices and target vector from dataframes.
    
    Parameters:
    -----------
    df1 : DataFrame
        First dataframe
    df2 : DataFrame
        Second dataframe
    feature_sets : list of dict
        List of feature set specifications. Each dict should have:
        - 'name': str, name for this feature set
        - 'df1_cols': list of str, columns from df1
        - 'df2_cols': list of str, columns from df2
    target_df : DataFrame
        DataFrame containing the target variable
    target_col : str
        Column name for the target variable
    
    Returns:
    --------
    feature_data : list of dict
        List of dictionaries, each containing:
        - 'name': feature set name
        - 'X': feature matrix
        - 'feature_names': list of feature names
    y : array-like
        Target vector (same for all feature sets)
    """
    # Extract target (same for all feature sets)
    y = target_df[target_col].values
    
    feature_data = []
    
    for feature_set in feature_sets:
        name = feature_set.get('name', 'Unnamed')
        df1_cols = feature_set.get('df1_cols', [])
        df2_cols = feature_set.get('df2_cols', [])
        
        # Extract features from each dataframe
        features_list = []
        feature_names = []
        
        if df1_cols:
            features_df1 = df1[df1_cols].values
            features_list.append(features_df1)
            feature_names.extend(df1_cols)
        
        if df2_cols:
            features_df2 = df2[df2_cols].values
            features_list.append(features_df2)
            feature_names.extend(df2_cols)
        
        # Combine features horizontally allowing for a single feature
        # (which otherwise defeats sklearn
        if features_list:
            if len(features_list) > 1:
                X = np.hstack(features_list)
            else:
                X = features_list[0]
                X = X.reshape(-1, 1)
                
        else:
            raise ValueError(f"Feature set '{name}' has no columns specified")
        
        feature_data.append({
            'name': name,
            'X': X,
            'feature_names': feature_names
        })
        
        print(f"  Feature set '{name}': {len(feature_names)} features - {feature_names}")
    
    return feature_data, y


def get_regression_models():
    """
    Define a dictionary of regression models to evaluate.
    
    Returns:
    --------
    dict : Dictionary with model names as keys and model instances as values
    """
    models = {
        'LinearRegression': LinearRegression(),
        'Ridge': Ridge(alpha=1.0),
        'Lasso': Lasso(alpha=1.0),
        'ElasticNet': ElasticNet(alpha=1.0, l1_ratio=0.5),
        # Added Linear SVR for comparison with the other linear
        # models. Parameters are the defaults from the scikit page.
        'Linear SVR': LinearSVR(C=1.0, epsilon=0, loss='squared_epsilon_insensitive'),
        # Reduce the alowable depth of decision trees
        #'DecisionTree': DecisionTreeRegressor(random_state=42, max_depth=5),
        'DecisionTree': DecisionTreeRegressor(random_state=42, max_depth=3),
        # Force random forest and GBR to use less estimators than datapoints.
        'RandomForest': RandomForestRegressor(n_estimators=3, random_state=42, max_depth=3),
        'GradientBoosting': GradientBoostingRegressor(n_estimators=3, random_state=42, max_depth=3),
        # USe different SVR kernels
        'SVR Radial': SVR(kernel='rbf', C=1.0, epsilon=0.1),
        'SVR Poly': SVR(kernel='poly', C=1.0, epsilon=0.1, degree=2),
        'SVR Sigmoid': SVR(kernel='sigmoid', C=1.0, epsilon=0.1),
        # Suspiciously high fit, suspect overfitting for single index
        #'XGB': XGBRegressor(enable_categorical=True, max_depth=3, tree_method='hist')
    }
    return models


def train_and_evaluate_regression(feature_data, y, models=None, output_file='model_results.csv'):
    """
    Train multiple regression models on multiple feature sets and compute evaluation metrics.
    
    Parameters:
    -----------
    feature_data : list of dict
        List of feature set data from build_feature_target_vectors
    y : array-like
        Target vector
    models : dict, optional
        Dictionary of models to train. If None, uses default models.
    output_file : str
        Path to output CSV file for results
    
    Returns:
    --------
    results_df : DataFrame
        DataFrame containing metrics for all models and feature sets
    trained_models : dict
        Dictionary of trained models (nested: feature_set -> model_name -> model)
    predictions : dict
        Dictionary of predictions (nested: feature_set -> model_name -> predictions)
    """
    if models is None:
        models = get_regression_models()
    
    results = []
    trained_models = {}
    predictions = {}
    
    print("\n" + "="*70)
    print("TRAINING AND EVALUATING MULTIPLE REGRESSION MODELS")
    print("="*70)
    
    # Iterate over each feature set
    for feat_set in feature_data:
        feat_name = feat_set['name']
        X = feat_set['X']
        feature_names = feat_set['feature_names']
        
        print(f"\n{'='*70}")
        print(f"FEATURE SET: {feat_name}")
        print(f"Features: {', '.join(feature_names)}")
        print(f"{'='*70}")
        
        trained_models[feat_name] = {}
        predictions[feat_name] = {}
        
        # Train each model on this feature set
        for model_name, model in models.items():
            print(f"  Training {model_name}...")
            
            # Train the model
            model_copy = type(model)(**model.get_params())  # Create fresh copy
            model_copy.fit(X, y)
            trained_models[feat_name][model_name] = model_copy
            
            # Make predictions
            y_pred = model_copy.predict(X)
            predictions[feat_name][model_name] = y_pred
            
            # Calculate metrics
            rmse = np.sqrt(mean_squared_error(y, y_pred))
            mae = mean_absolute_error(y, y_pred)
            r2 = r2_score(y, y_pred)
            
            # Store results
            result = {
                'FeatureSet': feat_name,
                'Features': ', '.join(feature_names),
                'NumFeatures': len(feature_names),
                'Model': model_name,
                'RMSE': rmse,
                'MAE': mae,
                'R²': r2,
                'Timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            }
            results.append(result)
            
            print(f"    RMSE: {rmse:.4f} | MAE: {mae:.4f} | R²: {r2:.4f}")
    
    # Create results DataFrame
    results_df = pd.DataFrame(results)

    # Not sure we want to sort, but will leave for now
    # Sort by R² (descending), then by feature set
    #results_df = results_df.sort_values(['R²', 'FeatureSet'], ascending=[False, True]).reset_index(drop=True)
    
    # Save to CSV
    results_df.to_csv(output_file, index=False)
    print(f"\n{'='*70}")
    print(f"Results saved to: {output_file}")
    print(f"{'='*70}")
    
    # Print summary table
    print("\nMODEL COMPARISON (sorted by R²):")
    print(results_df[['FeatureSet', 'Model', 'RMSE', 'MAE', 'R²']].to_string(index=False))
    print(f"{'='*70}\n")
    
    # Print "best" model for each feature set. Relies on the set
    # already having been sorted, so we do that here. We create a new
    # df since we don't want the output to be sorted.
    results_sorted = results_df.sort_values(['R²', 'FeatureSet'], ascending=[False, True]).reset_index(drop=True)
    
    print("BEST MODEL FOR EACH FEATURE SET:")
    print("="*70)
    for feat_name in results_sorted['FeatureSet'].unique():
        best = results_sorted[results_sorted['FeatureSet'] == feat_name].iloc[0]
        print(f"{feat_name}:")
        print(f"  Best Model: {best['Model']}")
        print(f"  R²: {best['R²']:.4f}, RMSE: {best['RMSE']:.4f}, MAE: {best['MAE']:.4f}")
    print("="*70 + "\n")
    
    return results_df, trained_models, predictions


def plot_regression_results(y_true, predictions, results_df, output_prefix='regression'):
    """
    Plot actual vs predicted values for multiple models and feature sets.
    
    Parameters:
    -----------
    y_true : array-like
        Actual target values
    predictions : dict
        Nested dictionary with feature_set -> model_name -> predictions
    results_df : DataFrame
        DataFrame containing model metrics
    output_prefix : str
        Prefix for saved plot files
    """
    # Plot best model for each feature set
    feature_sets = list(predictions.keys())
    n_feature_sets = len(feature_sets)
    
    fig, axes = plt.subplots(n_feature_sets, 3, figsize=(15, 5 * n_feature_sets))
    if n_feature_sets == 1:
        axes = axes.reshape(1, -1)
    
    for idx, feat_name in enumerate(feature_sets):
        # Get top 3 models for this feature set
        feat_results = results_df[results_df['FeatureSet'] == feat_name].head(3)
        
        for col_idx, (_, row) in enumerate(feat_results.iterrows()):
            if col_idx >= 3:
                break
                
            model_name = row['Model']
            y_pred = predictions[feat_name][model_name]
            
            ax = axes[idx, col_idx]
            
            # Plot actual vs predicted
            ax.scatter(y_true, y_pred, alpha=0.6, edgecolors='k', s=30)
            ax.plot([y_true.min(), y_true.max()], 
                   [y_true.min(), y_true.max()], 
                   'r--', lw=2, label='Perfect Prediction')
            
            ax.set_xlabel('Actual Values', fontsize=10)
            ax.set_ylabel('Predicted Values', fontsize=10)
            ax.set_title(f"{feat_name}\n{model_name} (R²={row['R²']:.4f})", 
                        fontsize=10, fontweight='bold')
            ax.legend(fontsize=8)
            ax.grid(True, alpha=0.3)
        
        # Hide unused subplots in this row
        for col_idx in range(len(feat_results), 3):
            axes[idx, col_idx].axis('off')
    
    plt.suptitle('Regression Model Comparison: Top 3 Models per Feature Set', 
                 fontsize=14, fontweight='bold', y=0.995)
    plt.tight_layout()
    
    # Save plot
    plot_file = f"{output_prefix}_comparison.png"
    plt.savefig(plot_file, dpi=300, bbox_inches='tight')
    print(f"Plot saved to: {plot_file}")
    plt.show()


def plot_feature_set_comparison(results_df, output_prefix='regression'):
    """
    Create bar plots comparing performance across feature sets.
    
    Parameters:
    -----------
    results_df : DataFrame
        DataFrame containing model metrics
    output_prefix : str
        Prefix for saved plot files
    """
    # Get best model for each feature set
    best_models = results_df.groupby('FeatureSet').first().reset_index()
    
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    metrics = ['R²', 'RMSE', 'MAE']
    colors = ['#2ecc71', '#e74c3c', '#f39c12']
    
    for idx, metric in enumerate(metrics):
        ax = axes[idx]
        
        bars = ax.bar(range(len(best_models)), best_models[metric], color=colors[idx], alpha=0.7, edgecolor='black')
        ax.set_xlabel('Feature Set', fontsize=12)
        ax.set_ylabel(metric, fontsize=12)
        ax.set_title(f'{metric} - Best Model per Feature Set', fontsize=12, fontweight='bold')
        ax.set_xticks(range(len(best_models)))
        ax.set_xticklabels(best_models['FeatureSet'], rotation=45, ha='right')
        ax.grid(True, alpha=0.3, axis='y')
        
        # Add value labels on bars
        for bar, val in zip(bars, best_models[metric]):
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{val:.3f}', ha='center', va='bottom', fontsize=9)
    
    plt.suptitle('Feature Set Performance Comparison', fontsize=14, fontweight='bold')
    plt.tight_layout()
    
    # Save plot
    plot_file = f"{output_prefix}_feature_comparison.png"
    plt.savefig(plot_file, dpi=300, bbox_inches='tight')
    print(f"Feature comparison plot saved to: {plot_file}")
    plt.show()


def parse_arguments():
    """
    Parse command-line arguments.
    
    Returns:
    --------
    args : Namespace
        Parsed arguments
    """
    parser = argparse.ArgumentParser(
        description='Train and evaluate multiple regression models on CSV data with multiple feature sets.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example usage:
  python build-regressions.py file1.csv file2.csv --output results.csv
  python build-regressions.py data1.csv data2.csv data3.csv --output my_results.csv --plot-prefix my_models
        """
    )
    
    parser.add_argument(
        'csv_files',
        nargs='+',
        help='One or more CSV files to read'
    )
    
    parser.add_argument(
        '--output',
        '-o',
        default='model_results.csv',
        help='Output CSV file for model results (default: model_results.csv)'
    )
    
    parser.add_argument(
        '--plot-prefix',
        '-p',
        default='regression',
        help='Prefix for output plot files (default: regression)'
    )
    
    parser.add_argument(
        '--no-plots',
        action='store_true',
        help='Disable plotting'
    )
    
    return parser.parse_args()


def main():
    """
    Main function demonstrating the complete workflow with command-line arguments.
    """
    # Parse command-line arguments
    args = parse_arguments()
    
    print("="*70)
    print("REGRESSION MODEL COMPARISON TOOL - MULTIPLE FEATURE SETS")
    print("="*70)
    print(f"Input files: {', '.join(args.csv_files)}")
    print(f"Output file: {args.output}")
    print(f"Plot prefix: {args.plot_prefix}")
    print("="*70)
    
    # Read CSV files
    dataframes = read_csv_files(args.csv_files)
    
    # Get the first two dataframes (you can modify this logic as needed)
    df_names = list(dataframes.keys())
    
    if len(df_names) < 2:
        print("\nError: At least 2 CSV files are required.")
        return

    # We will run with df1 as the index results and df2 as the yield
    # data. 
    df1 = dataframes[df_names[0]]
    df2 = dataframes[df_names[1]]
    
    # Display available columns
    print(f"\nColumns in {df_names[0]}: {list(df1.columns)}")
    print(f"Columns in {df_names[1]}: {list(df2.columns)}")
    
    # Define multiple feature sets to test
    # This is where you specify different combinations of features
    feature_sets = [
        {
            'name': 'ExG',
            'df1_cols': list(df1.columns)[1],
            'df2_cols': []
        },
        {
            'name': 'ExGR',
            'df1_cols': list(df1.columns)[2],  
            'df2_cols': []
        },
        {
            'name': 'GLI',
            'df1_cols': list(df1.columns)[3],  
            'df2_cols': []
        },
        { # VARI does not seem to be very helpful. Breaks SVR Poly
            'name': 'VARI',
            'df1_cols': list(df1.columns)[4],  
            'df2_cols': []
        },
        {
            'name': 'RGBVI',
            'df1_cols': list(df1.columns)[5],  
            'df2_cols': []
        },
        {
            'name': 'DCGI',
            'df1_cols': list(df1.columns)[6],  
            'df2_cols': []
        },
        {
            'name': 'NGBDI',
            'df1_cols': list(df1.columns)[7],  
            'df2_cols': []
        },
        {
            'name': 'BGR',
            'df1_cols': list(df1.columns)[8],  
            'df2_cols': []
        },
        {
            'name': 'GRVI',
            'df1_cols': list(df1.columns)[9],  
            'df2_cols': []
        },
        {
            'name': 'NRI',
            'df1_cols': list(df1.columns)[10],  
            'df2_cols': []
        },
        {
            'name': 'NGI',
            'df1_cols': list(df1.columns)[11],  
            'df2_cols': []
        },
        {
            'name': 'NBI',
            'df1_cols': list(df1.columns)[12],  
            'df2_cols': []
        },
        {
            'name': 'SAVI',
            'df1_cols': list(df1.columns)[13],  
            'df2_cols': []
        },
        {
            'name': 'GMR',
            'df1_cols': list(df1.columns)[14],  
            'df2_cols': []
        }
    ]
    
    # Target data. Column 4 of the yield file is Fresh_weight_2024_06_03
    target_col = df2.columns[4]
    
    print(f"\nTarget variable: {target_col} from {df_names[1]}")
    print(f"\nTesting {len(feature_sets)} different feature sets:")
    for fs in feature_sets:
        print(f"  - {fs['name']}")
    
    # Build feature and target vectors for all feature sets
    feature_data, y = build_feature_target_vectors(
        df1=df1,
        df2=df2,
        feature_sets=feature_sets,
        target_df=df2,
        target_col=target_col
    )
    
    # Train and evaluate multiple models on all feature sets
    results_df, trained_models, predictions = train_and_evaluate_regression(
        feature_data, y,
        output_file=args.output
    )
    
    # Plot results unless disabled
    if not args.no_plots:
        plot_regression_results(y, predictions, results_df, output_prefix=args.plot_prefix)
        plot_feature_set_comparison(results_df, output_prefix=args.plot_prefix)
    
    return dataframes, trained_models, results_df


def create_sample_data():
    """
    Helper function to create sample CSV files for testing.
    """
    print("Creating sample data files...")
    
    np.random.seed(42)
    n_samples = 200
    
    # Sample data for demonstration
    df1_sample = pd.DataFrame({
        'temperature': np.random.uniform(15, 35, n_samples),
        'humidity': np.random.uniform(30, 90, n_samples),
        'pressure': np.random.uniform(980, 1020, n_samples)
    })
    
    # Create target with some relationship to features
    noise = np.random.randn(n_samples) * 5
    target = (2.5 * df1_sample['temperature'] + 
              0.8 * df1_sample['humidity'] + 
              noise + 50)
    
    df2_sample = pd.DataFrame({
        'wind_speed': np.random.uniform(0, 25, n_samples),
        'visibility': np.random.uniform(1, 10, n_samples),
        'energy_consumption': target
    })
    
    # Save sample files
    df1_sample.to_csv('sample_weather.csv', index=False)
    df2_sample.to_csv('sample_energy.csv', index=False)
    
    print("Created sample_weather.csv and sample_energy.csv")
    print("\nTo run with sample data, use:")
    print("  python script.py sample_weather.csv sample_energy.csv")


if __name__ == "__main__":
    import sys
    
    # If no arguments provided, create sample data and show usage
    if len(sys.argv) == 1:
        print("No CSV files specified.\n")
        create_sample_data()
        print("\n" + "="*70)
        print("USAGE EXAMPLES:")
        print("="*70)
        print("python script.py sample_weather.csv sample_energy.csv")
        print("python script.py file1.csv file2.csv --output my_results.csv")
        print("python script.py data1.csv data2.csv --plot-prefix analysis --no-plots")
        print("="*70)
    else:
        dataframes, models, results = main()
