# build-regressions.py
#
# Code to analyse the data from the vegetative indices
#
# Simon Parsons
# University of Lincoln
# 26-03-27

# This is skeleton code to run regressions on the data that we
# generate from the vegetative indices. An intermediate version that
# handles categorical features and allows feature selection from the
# command line.

# Still needs work (though it runs in its current state). 

# Largely generated by Claude Sonnet 4.5

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import argparse
from pathlib import Path
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR, LinearSVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from datetime import datetime
# Use XGBoost to get categorical variable support
from xgboost import XGBRegressor
# To handle categorical features
from sklearn.preprocessing import OneHotEncoder
# To parse feature sets
import json

def read_csv_files(file_paths):
    """
    Read one or more CSV files into pandas DataFrames.
    
    Parameters:
    -----------
    file_paths : list of str
        List of file paths to CSV files
    
    Returns:
    --------
    dict : Dictionary with file names as keys and DataFrames as values
    """
    dataframes = {}
    for file_path in file_paths:
        file_name = Path(file_path).stem
        dataframes[file_name] = pd.read_csv(file_path)
        print(f"Loaded {file_name}: {dataframes[file_name].shape}")
    
    return dataframes


def build_feature_target_vectors(df1, df2, feature_sets, target_df, target_col, categorical_features=None):
    """
    Build multiple feature matrices and target vector from dataframes.
    
    Parameters:
    -----------
    df1 : DataFrame
        First dataframe
    df2 : DataFrame
        Second dataframe
    feature_sets : list of dict
        List of feature set specifications. Each dict should have:
        - 'name': str, name for this feature set
        - 'df1_cols': list of str, columns from df1
        - 'df2_cols': list of str, columns from df2
    target_df : DataFrame
        DataFrame containing the target variable
    target_col : str
        Column name for the target variable
    categorical_features : dict, optional
        Dictionary mapping dataframe names to lists of categorical column names
        Example: {'df1': ['color', 'size'], 'df2': ['category']}
    
    Returns:
    --------
    feature_data : list of dict
        List of dictionaries, each containing:
        - 'name': feature set name
        - 'X': feature matrix
        - 'feature_names': list of feature names
    y : array-like
        Target vector (same for all feature sets)
    """
    # Extract target (same for all feature sets)
    y = target_df[target_col].values
    
    feature_data = []

    # Initialize categorical features dict if not provided
    if categorical_features is None:
        categorical_features = {'df1': [], 'df2': []}
        
    for feature_set in feature_sets:
        name = feature_set.get('name', 'Unnamed')
        df1_cols = feature_set.get('df1_cols', [])
        df2_cols = feature_set.get('df2_cols', [])
        
        # Extract features from each dataframe and store encoders for
        # the features.
        features_list = []
        feature_names = []
        encoders = {}
        
        # Process dataframes taking account of categorical features
        # Process df1 columns
        if df1_cols:
            df1_categorical = [col for col in df1_cols if col in categorical_features.get('df1', [])]
            df1_numerical = [col for col in df1_cols if col not in df1_categorical]
            
            # Add numerical features
            if df1_numerical:
                features_df1_num = df1[df1_numerical].values
                features_list.append(features_df1_num)
                feature_names.extend(df1_numerical)
            
            # Add categorical features (one-hot encoded)
            if df1_categorical:
                for cat_col in df1_categorical:
                    encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
                    encoded = encoder.fit_transform(df1[[cat_col]])
                    features_list.append(encoded)
                    
                    # Generate feature names for one-hot encoded columns
                    cat_names = [f"{cat_col}_{cat}" for cat in encoder.categories_[0]]
                    feature_names.extend(cat_names)
                    encoders[f'df1_{cat_col}'] = encoder
                    
                    print(f"    One-hot encoded '{cat_col}' from df1: {len(encoder.categories_[0])} categories")

        # Process df2 columns with categorical encoding
        if df2_cols:
            df2_categorical = [col for col in df2_cols if col in categorical_features.get('df2', [])]
            df2_numerical = [col for col in df2_cols if col not in df2_categorical]
            
            # Add numerical features
            if df2_numerical:
                features_df2_num = df2[df2_numerical].values
                features_list.append(features_df2_num)
                feature_names.extend(df2_numerical)
            
            # Add categorical features (one-hot encoded)
            if df2_categorical:
                for cat_col in df2_categorical:
                    encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
                    encoded = encoder.fit_transform(df2[[cat_col]])
                    features_list.append(encoded)
                    
                    # Generate feature names for one-hot encoded columns
                    cat_names = [f"{cat_col}_{cat}" for cat in encoder.categories_[0]]
                    feature_names.extend(cat_names)
                    encoders[f'df2_{cat_col}'] = encoder
                    
                    print(f"    One-hot encoded '{cat_col}' from df2: {len(encoder.categories_[0])} categories")
                    
        # Combine features horizontally allowing for a single feature
        # (which otherwise defeats sklearn
        if features_list:
            if len(features_list) > 1:
                X = np.hstack(features_list)
            else:
                X = features_list[0]
                X = X.reshape(-1, 1)
        else:
            raise ValueError(f"Feature set '{name}' has no columns specified")
        
        feature_data.append({
            'name': name,
            'X': X,
            'feature_names': feature_names,
            'encoders': encoders
        })
        
        print(f"  Feature set '{name}': {len(feature_names)} features - {feature_names}")
    
    return feature_data, y


def get_regression_models():
    """
    Define a dictionary of regression models to evaluate.
    
    Returns:
    --------
    dict : Dictionary with model names as keys and model instances as values
    """
    models = {
        'LinearRegression': LinearRegression(),
        'Ridge': Ridge(alpha=1.0),
        'Lasso': Lasso(alpha=1.0),
        'ElasticNet': ElasticNet(alpha=1.0, l1_ratio=0.5),
        # Added Linear SVR for comparison with the other linear
        # models. Parameters are the defaults from the scikit page.
        'Linear SVR': LinearSVR(C=1.0, epsilon=0, loss='squared_epsilon_insensitive'),
        # Reduce the alowable depth of decision trees
        #'DecisionTree': DecisionTreeRegressor(random_state=42, max_depth=5),
        'DecisionTree': DecisionTreeRegressor(random_state=42, max_depth=3),
        # Force random forest and GBR to use less estimators than datapoints.
        'RandomForest': RandomForestRegressor(n_estimators=3, random_state=42, max_depth=3),
        'GradientBoosting': GradientBoostingRegressor(n_estimators=3, random_state=42, max_depth=3),
        # USe different SVR kernels
        'SVR Radial': SVR(kernel='rbf', C=1.0, epsilon=0.1),
        'SVR Poly': SVR(kernel='poly', C=1.0, epsilon=0.1, degree=2),
        'SVR Sigmoid': SVR(kernel='sigmoid', C=1.0, epsilon=0.1),
        # Suspiciously high fit, suspect overfitting for single index
        #'XGB': XGBRegressor(enable_categorical=True, max_depth=3, tree_method='hist')
    }
    return models


def train_and_evaluate_regression(feature_data, y, models=None, output_file='model_results.csv'):
    """
    Train multiple regression models on multiple feature sets and compute evaluation metrics.
    
    Parameters:
    -----------
    feature_data : list of dict
        List of feature set data from build_feature_target_vectors
    y : array-like
        Target vector
    models : dict, optional
        Dictionary of models to train. If None, uses default models.
    output_file : str
        Path to output CSV file for results
    
    Returns:
    --------
    results_df : DataFrame
        DataFrame containing metrics for all models and feature sets
    trained_models : dict
        Dictionary of trained models (nested: feature_set -> model_name -> model)
    predictions : dict
        Dictionary of predictions (nested: feature_set -> model_name -> predictions)
    """
    if models is None:
        models = get_regression_models()
    
    results = []
    trained_models = {}
    predictions = {}
    
    print("\n" + "="*70)
    print("TRAINING AND EVALUATING MULTIPLE REGRESSION MODELS")
    print("="*70)
    
    # Iterate over each feature set
    for feat_set in feature_data:
        feat_name = feat_set['name']
        X = feat_set['X']
        feature_names = feat_set['feature_names']
        
        print(f"\n{'='*70}")
        print(f"FEATURE SET: {feat_name}")
        print(f"Features: {', '.join(feature_names)}")
        print(f"{'='*70}")
        
        trained_models[feat_name] = {}
        predictions[feat_name] = {}
        
        # Train each model on this feature set
        for model_name, model in models.items():
            print(f"  Training {model_name}...")
            
            # Train the model
            model_copy = type(model)(**model.get_params())  # Create fresh copy
            model_copy.fit(X, y)
            trained_models[feat_name][model_name] = model_copy
            
            # Make predictions
            y_pred = model_copy.predict(X)
            predictions[feat_name][model_name] = y_pred
            
            # Calculate metrics
            rmse = np.sqrt(mean_squared_error(y, y_pred))
            mae = mean_absolute_error(y, y_pred)
            r2 = r2_score(y, y_pred)
            
            # Store results
            result = {
                'FeatureSet': feat_name,
                'Features': ', '.join(feature_names),
                'NumFeatures': len(feature_names),
                'Model': model_name,
                'RMSE': rmse,
                'MAE': mae,
                'R²': r2,
                'Timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            }
            results.append(result)
            
            print(f"    RMSE: {rmse:.4f} | MAE: {mae:.4f} | R²: {r2:.4f}")
    
    # Create results DataFrame
    results_df = pd.DataFrame(results)

    # Not sorting hre though this code allows us to if desired.  
    #results_df = results_df.sort_values(['R²', 'FeatureSet'], ascending=[False, True]).reset_index(drop=True)
    
    # Save to CSV
    results_df.to_csv(output_file, index=False)
    print(f"\n{'='*70}")
    print(f"Results saved to: {output_file}")
    print(f"{'='*70}")
    
    # Print summary table
    print("\nMODEL COMPARISON (sorted by R²):")
    print(results_df[['FeatureSet', 'Model', 'RMSE', 'MAE', 'R²']].to_string(index=False))
    print(f"{'='*70}\n")
    
    # Print "best" model for each feature set. Relies on the set
    # already having been sorted, so we do that here. We create a new
    # df in case we later need the unsorted one.
    results_sorted = results_df.sort_values(['R²', 'FeatureSet'], ascending=[False, True]).reset_index(drop=True)
    
    print("BEST MODEL FOR EACH FEATURE SET:")
    print("="*70)
    for feat_name in results_sorted['FeatureSet'].unique():
        best = results_sorted[results_sorted['FeatureSet'] == feat_name].iloc[0]
        print(f"{feat_name}:")
        print(f"  Best Model: {best['Model']}")
        print(f"  R²: {best['R²']:.4f}, RMSE: {best['RMSE']:.4f}, MAE: {best['MAE']:.4f}")
    print("="*70 + "\n")
    
    return results_df, trained_models, predictions


def plot_regression_results(y_true, predictions, results_df, output_prefix='regression'):
    """
    Plot actual vs predicted values for multiple models and feature sets.
    
    Parameters:
    -----------
    y_true : array-like
        Actual target values
    predictions : dict
        Nested dictionary with feature_set -> model_name -> predictions
    results_df : DataFrame
        DataFrame containing model metrics
    output_prefix : str
        Prefix for saved plot files
    """
    # Plot best model for each feature set
    feature_sets = list(predictions.keys())
    n_feature_sets = len(feature_sets)
    
    fig, axes = plt.subplots(n_feature_sets, 3, figsize=(15, 5 * n_feature_sets))
    if n_feature_sets == 1:
        axes = axes.reshape(1, -1)
    
    for idx, feat_name in enumerate(feature_sets):
        # Get top 3 models for this feature set
        feat_results = results_df[results_df['FeatureSet'] == feat_name].head(3)
        
        for col_idx, (_, row) in enumerate(feat_results.iterrows()):
            if col_idx >= 3:
                break
                
            model_name = row['Model']
            y_pred = predictions[feat_name][model_name]
            
            ax = axes[idx, col_idx]
            
            # Plot actual vs predicted
            ax.scatter(y_true, y_pred, alpha=0.6, edgecolors='k', s=30)
            ax.plot([y_true.min(), y_true.max()], 
                   [y_true.min(), y_true.max()], 
                   'r--', lw=2, label='Perfect Prediction')
            
            ax.set_xlabel('Actual Values', fontsize=10)
            ax.set_ylabel('Predicted Values', fontsize=10)
            ax.set_title(f"{feat_name}\n{model_name} (R²={row['R²']:.4f})", 
                        fontsize=10, fontweight='bold')
            ax.legend(fontsize=8)
            ax.grid(True, alpha=0.3)
        
        # Hide unused subplots in this row
        for col_idx in range(len(feat_results), 3):
            axes[idx, col_idx].axis('off')
    
    plt.suptitle('Regression Model Comparison: Top 3 Models per Feature Set', 
                 fontsize=14, fontweight='bold', y=0.995)
    plt.tight_layout()
    
    # Save plot
    plot_file = f"{output_prefix}_comparison.png"
    plt.savefig(plot_file, dpi=300, bbox_inches='tight')
    print(f"Plot saved to: {plot_file}")
    plt.show()


def plot_feature_set_comparison(results_df, output_prefix='regression'):
    """
    Create bar plots comparing performance across feature sets.
    
    Parameters:
    -----------
    results_df : DataFrame
        DataFrame containing model metrics
    output_prefix : str
        Prefix for saved plot files
    """
    # Get best model for each feature set
    best_models = results_df.groupby('FeatureSet').first().reset_index()
    
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    metrics = ['R²', 'RMSE', 'MAE']
    colors = ['#2ecc71', '#e74c3c', '#f39c12']
    
    for idx, metric in enumerate(metrics):
        ax = axes[idx]
        
        bars = ax.bar(range(len(best_models)), best_models[metric], color=colors[idx], alpha=0.7, edgecolor='black')
        ax.set_xlabel('Feature Set', fontsize=12)
        ax.set_ylabel(metric, fontsize=12)
        ax.set_title(f'{metric} - Best Model per Feature Set', fontsize=12, fontweight='bold')
        ax.set_xticks(range(len(best_models)))
        ax.set_xticklabels(best_models['FeatureSet'], rotation=45, ha='right')
        ax.grid(True, alpha=0.3, axis='y')
        
        # Add value labels on bars
        for bar, val in zip(bars, best_models[metric]):
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{val:.3f}', ha='center', va='bottom', fontsize=9)
    
    plt.suptitle('Feature Set Performance Comparison', fontsize=14, fontweight='bold')
    plt.tight_layout()
    
    # Save plot
    plot_file = f"{output_prefix}_feature_comparison.png"
    plt.savefig(plot_file, dpi=300, bbox_inches='tight')
    print(f"Feature comparison plot saved to: {plot_file}")
    plt.show()

# Parse feature set specifications from command line
def parse_feature_set_spec(spec_string):
    """
    Parse a feature set specification string.
    
    Format: name:df1_col1,df1_col2:df2_col1,df2_col2
    
    Parameters:
    -----------
    spec_string : str
        Feature set specification string
    
    Returns:
    --------
    dict : Feature set dictionary
    """
    parts = spec_string.split(':')
    if len(parts) != 3:
        raise ValueError(f"Invalid feature set format: {spec_string}\n"
                        "Expected format: name:df1_col1,df1_col2:df2_col1,df2_col2")
    
    name = parts[0]
    df1_cols = [col.strip() for col in parts[1].split(',') if col.strip()]
    df2_cols = [col.strip() for col in parts[2].split(',') if col.strip()]
    
    return {
        'name': name,
        'df1_cols': df1_cols,
        'df2_cols': df2_cols
    }

def parse_arguments():
    """
    Parse command-line arguments.
    
    Returns:
    --------
    args : Namespace
        Parsed arguments
    """
    parser = argparse.ArgumentParser(
        description='Train and evaluate multiple regression models on CSV data with multiple feature sets.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example usage:
  # Basic usage with feature sets
  python script.py file1.csv file2.csv \\
    --feature-set "Set1:temp,humidity:wind,pressure" \\
    --feature-set "Set2:temp:wind" \\
    --target energy_consumption
  
  # With categorical features
  python script.py weather.csv energy.csv \\
    --feature-set "AllFeatures:temp,humidity,season:wind,time_of_day" \\
    --categorical df1:season df2:time_of_day \\
    --target energy_consumption
  
  # Multiple feature sets with categorical features
  python script.py data1.csv data2.csv \\
    --feature-set "Numeric:temp,humidity:" \\
    --feature-set "WithCategory:temp,season:wind" \\
    --categorical df1:season \\
    --target outcome \\
    --output results.csv

Feature set format: name:df1_col1,df1_col2:df2_col1,df2_col2
  - name: Name for this feature set
  - First colon separates name from df1 columns
  - Second colon separates df1 columns from df2 columns
  - Columns within each dataframe are comma-separated
  - Leave empty (e.g., "Set:col1,col2:") if no columns from that dataframe

Categorical format: df_name:col1,col2,col3
  - df_name should be 'df1' or 'df2'
  - Columns are comma-separated
        """
    )
    
    parser.add_argument(
        'csv_files',
        nargs='+',
        help='One or more CSV files to read'
    )
    
    # NEW: Feature set specification
    parser.add_argument(
        '--feature-set',
        '-f',
        action='append',
        dest='feature_sets',
        help='Feature set specification (format: name:df1_cols:df2_cols). Can be specified multiple times.'
    )
    
    # NEW: Target column specification
    parser.add_argument(
        '--target',
        '-t',
        required=True,
        help='Target column name (must exist in one of the dataframes)'
    )
    
    # NEW: Categorical feature specification
    parser.add_argument(
        '--categorical',
        '-c',
        action='append',
        dest='categorical',
        help='Categorical features (format: df_name:col1,col2). Can be specified multiple times.'
    )

    parser.add_argument(
        '--output',
        '-o',
        default='model_results.csv',
        help='Output CSV file for model results (default: model_results.csv)'
    )
    
    parser.add_argument(
        '--plot-prefix',
        '-p',
        default='regression',
        help='Prefix for output plot files (default: regression)'
    )
    
    parser.add_argument(
        '--no-plots',
        action='store_true',
        help='Disable plotting'
    )
    
    return parser.parse_args()
   
def main():
    """
    Main function demonstrating the complete workflow with command-line arguments.
    """
    # Parse command-line arguments
    args = parse_arguments()
    
    print("="*70)
    print("REGRESSION MODEL COMPARISON TOOL - MULTIPLE FEATURE SETS")
    print("="*70)
    print(f"Input files: {', '.join(args.csv_files)}")
    print(f"Output file: {args.output}")
    print(f"Plot prefix: {args.plot_prefix}")
    print("="*70)
    
    # Read CSV files
    dataframes = read_csv_files(args.csv_files)
    
    # Get the first two dataframes 
    df_names = list(dataframes.keys())
    
    if len(df_names) < 2:
        print("\nError: At least 2 CSV files are required.")
        return

    # We will run with df1 as the index results and df2 as the yield
    # data. 
    df1 = dataframes[df_names[0]]
    df2 = dataframes[df_names[1]]
    
    # Parse feature sets from command line
    if args.feature_sets:
        feature_sets = []
        print("\nParsing feature sets from command line:")
        for spec in args.feature_sets:
            try:
                fs = parse_feature_set_spec(spec)
                feature_sets.append(fs)
                print(f"  - {fs['name']}: df1={fs['df1_cols']}, df2={fs['df2_cols']}")
            except ValueError as e:
                print(f"Error parsing feature set: {e}")
                return
    else:
        # Default feature sets if none specified
        print("\nNo feature sets specified. Using default feature sets.")
        feature_sets = [
            {
                'name': 'Set1_First2Cols',
                'df1_cols': list(df1.columns)[:2],
                'df2_cols': list(df2.columns)[:2]
            }
        ]

    # Parse categorical features from command line
    categorical_features = {'df1': [], 'df2': []}
    if args.categorical:
        print("\nParsing categorical features:")
        for cat_spec in args.categorical:
            parts = cat_spec.split(':')
            if len(parts) != 2:
                print(f"Error: Invalid categorical format: {cat_spec}")
                print("Expected format: df_name:col1,col2")
                return
            
            df_name = parts[0].strip()
            cols = [col.strip() for col in parts[1].split(',') if col.strip()]
            
            if df_name not in ['df1', 'df2']:
                print(f"Error: df_name must be 'df1' or 'df2', got '{df_name}'")
                return
            
            categorical_features[df_name].extend(cols)
            print(f"  - {df_name}: {cols}")

    # Find target column in dataframes
    target_df = None
    if args.target in df1.columns:
        target_df = df1
        print(f"\nTarget '{args.target}' found in {df_names[0]}")
    elif args.target in df2.columns:
        target_df = df2
        print(f"\nTarget '{args.target}' found in {df_names[1]}")
    else:
        print(f"\nError: Target column '{args.target}' not found in any dataframe")
        return
    
    # Pass categorical_features to build_feature_target_vectors
    print(f"\nTesting {len(feature_sets)} different feature sets:")
    for fs in feature_sets:
        print(f"  - {fs['name']}")
    
    # Build feature and target vectors for all feature sets
    feature_data, y = build_feature_target_vectors(
        df1=df1,
        df2=df2,
        feature_sets=feature_sets,
        target_df=target_df,
        target_col=args.target,
        categorical_features=categorical_features)
    
    # Train and evaluate multiple models on all feature sets
    results_df, trained_models, predictions = train_and_evaluate_regression(
        feature_data, y,
        output_file=args.output
    )
    
    # Plot results unless disabled
    if not args.no_plots:
        plot_regression_results(y, predictions, results_df, output_prefix=args.plot_prefix)
        plot_feature_set_comparison(results_df, output_prefix=args.plot_prefix)
    
    return dataframes, trained_models, results_df

def create_sample_data():
    """
    Helper function to create sample CSV files for testing.
    """
    print("Creating sample data files with categorical features...")
    
    np.random.seed(42)
    n_samples = 200
    
    # NEW: Sample data with categorical features
    df1_sample = pd.DataFrame({
        'temperature': np.random.uniform(15, 35, n_samples),
        'humidity': np.random.uniform(30, 90, n_samples),
        'pressure': np.random.uniform(980, 1020, n_samples),
        'season': np.random.choice(['Spring', 'Summer', 'Fall', 'Winter'], n_samples)  # NEW: Categorical
    })
    
    # Create target with some relationship to features and season
    season_effect = {'Spring': 0, 'Summer': 20, 'Fall': 10, 'Winter': -10}
    season_values = df1_sample['season'].map(season_effect).values
    
    noise = np.random.randn(n_samples) * 5
    target = (2.5 * df1_sample['temperature'] + 
              0.8 * df1_sample['humidity'] + 
              season_values +
              noise + 50)
    
    df2_sample = pd.DataFrame({
        'wind_speed': np.random.uniform(0, 25, n_samples),
        'visibility': np.random.uniform(1, 10, n_samples),
        'time_of_day': np.random.choice(['Morning', 'Afternoon', 'Evening', 'Night'], n_samples),  # NEW: Categorical
        'energy_consumption': target
    })
    
    # Save sample files
    df1_sample.to_csv('sample_weather.csv', index=False)
    df2_sample.to_csv('sample_energy.csv', index=False)
    
    print("Created sample_weather.csv and sample_energy.csv")
    print("\nSample data includes categorical features:")
    print("  - sample_weather.csv: 'season' (Spring/Summer/Fall/Winter)")
    print("  - sample_energy.csv: 'time_of_day' (Morning/Afternoon/Evening/Night)")
    print("\nTo run with sample data, use:")
    print("  python script.py sample_weather.csv sample_energy.csv \\")
    print("    --feature-set 'Numeric:temperature,humidity:wind_speed' \\")
    print("    --feature-set 'WithSeason:temperature,season:wind_speed' \\")
    print("    --categorical df1:season \\")
    print("    --target energy_consumption")


if __name__ == "__main__":
    import sys
    
    # If no arguments provided, create sample data and show usage
    if len(sys.argv) == 1:
        print("No CSV files specified.\n")
        create_sample_data()
        print("\n" + "="*70)
        print("USAGE EXAMPLES:")
        print("="*70)
        print("\n# Example 1: Basic usage with numeric features")
        print("python script.py sample_weather.csv sample_energy.csv \\")
        print("  --feature-set 'Basic:temperature,humidity:wind_speed' \\")
        print("  --target energy_consumption")
        
        print("\n# Example 2: With categorical features")
        print("python script.py sample_weather.csv sample_energy.csv \\")
        print("  --feature-set 'WithCategory:temperature,season:wind_speed,time_of_day' \\")
        print("  --categorical df1:season \\")
        print("  --categorical df2:time_of_day \\")
        print("  --target energy_consumption")
        
        print("\n# Example 3: Multiple feature sets")
        print("python script.py sample_weather.csv sample_energy.csv \\")
        print("  --feature-set 'Numeric:temperature,humidity:wind_speed' \\")
        print("  --feature-set 'WithSeason:temperature,humidity,season:wind_speed' \\")
        print("  --feature-set 'AllFeatures:temperature,humidity,season:wind_speed,time_of_day' \\")
        print("  --categorical df1:season \\")
        print("  --categorical df2:time_of_day \\")
        print("  --target energy_consumption \\")
        print("  --output my_results.csv")
        print("="*70)
    else:
        dataframes, models, results = main()

